data:
  build: omero-data
  command: true
  volumes:
    - /data

pg:
  build: omero-postgres
  volumes_from:
    - data
  environment:
    - PGDATA=/data/postgres

omeroserver:
  build: omero-server
  volumes_from:
    - data
  links:
    - pg:pg
  ports:
    - "4064:4064"

omeroweb:
  build: omero-web
  links:
    - omeroserver:omero_server
  ports:
    - "80:80"

# datashell:
#   build: omero-data
#   command: sh
#   volumes_from:
#     - data

# backup:
#   build: omero-data
#   command: tar -cvf /tmp/${BACKUP_NAME:backup.tar} /data
#   volumes_from:
#     - data
#   volumes:
#     - ${BACKUP_DIR:tmp}:/tmp
