omero-data:
  container_name: omero-data
  build: omero-data
  command: "true"
  privileged: true
  volumes:
    - ${OMERO_DATA_DIR}:/data:Z

omero-pg:
  container_name: omero-pg
  build: omero-postgres
  volumes_from:
    - omero-data
  environment:
    - PGDATA=/data/postgres

omero-server:
  container_name: omero-server
  build: omero-server
  volumes_from:
    - omero-data
  links:
    - omero-pg:omero-pg
  ports:
    - "${OMERO_SERVER_PORT}:4064"

omero-web:
  container_name: omero-web
  build: omero-web
  volumes_from:
    - omero-data
  links:
    - omero-server:omero_server
  ports:
    - "${OMERO_WEB_PORT}:80"
    - "${OMERO_WEB_PORT_SSL}:443"
    - "${OMERO_WEB_PORT_DEVELOPMENT}:4080"
  environment:
    - OMERO_WEB_USE_SSL=${OMERO_WEB_USE_SSL}
    - OMERO_WEB_DEVELOPMENT=${OMERO_WEB_DEVELOPMENT}
